name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Recommended for SonarQube or similar tools for full history

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven # Caches Maven dependencies for faster builds

    - name: Build with Maven
      run: mvn -B package --file pom.xml # -B for batch mode, --file to explicitly specify pom.xml
